apiVersion: apps/v1
kind: Deployment
metadata:
    name: sp-web-deployment
    labels:
        app: sp-web
spec:
    replicas: 1
    selector:
        matchLabels:
            app: sp-web
    template:
        metadata:
            labels:
                app: sp-web
        spec:
            containers:
                - name: sp-web
                  image: swotong/same-page-web:latest
                  ports:
                      - containerPort: 80
