apiVersion: v1
kind: Service
metadata:
    name: sp-web-svc
    labels:
        app: sp-web
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP
    selector:
        app: sp-web
